### ISSUE TITLE
Image Styles - Regular, wide and full.

### ISSUE THREAD

**Issue by duncanjbain** [huangyuzhang/Fizzy-Theme#22]
First off, great theme! I'm just starting out with my blog and I'll be using this for sure!

I've just been trialling some things and comparing them to the Casper theme (and maybe others?). 

When setting an image to be 'wide', the image shows slightly wider in the editor but when I view the image, the image seems to have the behaviour of a 'full' width image.

See https://duncanbain.io/blog/test-post/

Is this intended behaviour? I would have thought setting 'wide' would have the image slightly larger than the content area, as with Casper. But not full width like 'full'.

**Comment by huangyuzhang** [comment]
@duncanjbain Thank you for considering using Fizzy Theme. 

The problem you mentioned is a bug, I will fix that soon. 

The problem is caused because I have only tested to embed images from Unsplash which the image is automatically cropped with 1080px wide. But apparently uploaded images won't be cropped.

Thank you for posting this bug!

**Comment by duncanjbain** [comment]
Great! I had a quick look at implementing it, but I see you've already pushed a fix :)

**Comment by huangyuzhang** [comment]
Yep, I had a quick fix with that, but feel free to implement a better or elegant way to do that and post a PR. 
Cheers.
