### ISSUE TITLE
Run in Local Dev [yarn, gulp dev commands]

### ISSUE THREAD

**Issue by venkatamandala** [huangyuzhang/Fizzy-Theme#28]
Hi, This theme is great. Are there steps for local development? yarn install, yarn dev commands doesn;t work and there is no gulp.js file to run gulp commands. How to run this in local dev mode and make changes ? Please help

**Comment by venkatamandala** [comment]
I think i found it below . is there any other detailed documentation some where else? Just checking. Thank you.

https://fizzy.cc/gulp-theme-workflow/

**Comment by huangyuzhang** [comment]
Sorry, I have been pretty busy these days. Yes, you could use that as a way to do the local development, even though I have made some modifications to it. The reason I didn't provide the gulp file in the repo is that the local development setup for this theme is relatively easy since I use cdn for all css and js packages. Feel free to customize it your way.

PS. Thanks for the star!!
